name: flutter_solidart_testapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_solidart: ^1.0.0
  uuid: ^3.0.7
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  http: ^1.1.0
  meta: ^1.9.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  solidart_lint: ^1.0.1
  custom_lint: ^0.5.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
flutter:
  uses-material-design: true
